config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get :concepts, to: 'concepts#index'

  devise_for :pharmacists, controllers: {
                            sessions:      'pharmacists/sessions',
                            passwords:     'pharmacists/passwords',
                            registrations: 'pharmacists/registrations'
                          }, path_names: {
                            sign_in: 'login', sign_out: 'logout'
                          }
  devise_for :students, controllers: {
                          sessions:      'students/sessions',
                          passwords:     'students/passwords',
                          registrations: 'students/registrations'
                        }, path_names: {
                          sign_in: 'login', sign_out: 'logout'
                        }

  devise_scope :pharmacist do
    post 'pharmacists/guest_log_in', to: 'pharmacists/sessions#new_guest'
  end

  devise_scope :student do
    post 'students/guest_log_in', to: 'students/sessions#new_guest'
  end

  resources :pharmacists, only: :show
  resources :students, only: :show
  resources :pharmacist_profiles, except: [:index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :student_profiles, except: [:index, :destroy]

  resources :relationships, only: [:create, :update, :destroy]

  resources :rooms, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_account_delete_modal.html.erb
<div id="popup_account_delete" class="popup">
  <div class="popup_inner">
    <div id="account_delete_close" class="close_btn"><i class="fas fa-times" aria-hidden="true"></i></div>
    <h2>アカウントを削除しますか？</h2>
    <p>アカウントを削除すると、</p>
    <p>全てのデータが失われます。</p>
    <%= link_to "アカウントを削除する", registration_path(resource_name), method: :delete, class: "cancel_btn" %>
    <a id="account_delete_back" class="back_btn">戻る</a>
  </div>
  <div id="account_delete_black" class="bg_black"></div>
</div>

app/views/shared/_account_edit_page.html.erb
<% provide(:title, "アカウント編集") %>
<% content_for :js do %>
  <%= javascript_pack_tag 'accounts/delete', 'data-turbolinks-track': 'reload' %>
<% end %>
<div class="form">
  <h2>アカウント編集</h2>

  <div class="form_contents">
    <%= form_with model: resource, scope: resource_name, url: registration_path(resource_name), method: :put do |f| %>
      <%= render "shared/error_messages", resource: resource %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
      <% end %>

      <div class="field">
        <%= f.label :password %> (パスワードを変更しない場合は入力不要)<br />
        <%= f.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %> (パスワードを変更しない場合は入力不要)<br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
      </div>

      <div class="field">
        <%= f.label :current_password %> <br />
        <%= f.password_field :current_password, autocomplete: "current-password" %>
      </div>

      <div class="actions">
        <%= f.submit "更新", class: "btn"%>
      </div>
    <% end %>

    <p>アカウントを削除して退会する</p>

    <p class="cancel_btn js_account_delete">アカウント削除</p>
      <%= render "shared/account_delete_modal", resource: resource %>
  </div>
</div>

app/views/shared/_end_talk_modal.html.erb
<div id="popup_end_talk" class="popup">
  <div class="popup_inner">
    <div id="end_talk_close" class="close_btn"><i class="fas fa-times" aria-hidden="true"></i></div>
    <h2>トークを終了しますか？</h2>
    <p>トークを終了すると、</p>
    <p>会話の内容は全て削除されます。</p>
    <div class="end_or_back">
      <%= link_to "トークを終了する", room_path(room), method: :delete, class: "cancel_btn" %>
      <a id="end_talk_back" class="back_btn">戻る</a>
    </div>
  </div>
  <div id="end_talk_black" class="bg_black"></div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <%# <h3> %>
      <%#= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    <%# </h3> %>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if flash[:error] %>
  <ul class="error">
    <% flash[:error].each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "登録済みの方はログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録はこちら", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_log_in.html.erb
<%= render "shared/flash" %>
<div class="form">
  <h2>ログイン</h2>
  <div class="form_contents">
    <%= form_with model: resource, scope: resource_name, url: session_path(resource_name) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>

      <% if devise_mapping.rememberable? %>
        <div class="check_box">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "ログイン", class: "btn" %>
      </div>
    <% end %>

    <%= render "shared/links" %>
  </div>
</div>

app/views/shared/_log_in_modal.html.erb
<div id="popup_log_in" class="popup">
  <div class="popup_inner">
    <div id="log_in_close" class="close_btn"><i class="fas fa-times" aria-hidden="true"></i></div>
    <h2 class="title_border">ログイン</h2>
    <p>あなたは薬剤師ですか？</p>
    <p>学生ですか？</p>
    <%= link_to "薬剤師", new_pharmacist_session_path, class:"btn" %>
    <%= link_to "学生", new_student_session_path, class:"btn" %>
  </div>
  <div id="log_in_black" class="bg_black"></div>
</div>

app/views/shared/_log_in_page.html.erb
<% provide(:title, "ログイン") %>
<%= render "shared/flash" %>
<div class="form">
  <h2>ログイン(<%= user_type %>)</h2>
  <div class="form_contents">
    <%= form_with model: resource, scope: resource_name, url: session_path(resource_name) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>

      <% if devise_mapping.rememberable? %>
        <div class="check_box">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "ログイン", class: "btn" %>
      </div>
    <% end %>

    <p class="test_user"><%= link_to "テストユーザーでログイン", guest_log_in_path, method: :post %></p>


    <%= render "shared/links" %>
  </div>
</div>
<%= render "shared/sign_up_modal" %>
<%= render "shared/log_in_modal" %>

app/views/shared/_modal.html.erb
<div id="popup" class="popup">
  <div class="popup_inner">
    <div id="close_btn" class="close_btn"><i class="fas fa-times" aria-hidden="true"></i></div>
    <h2 class="title_border">新規会員登録</h2>
    <p>あなたは薬剤師ですか？</p>
    <p>学生ですか？</p>
    <%= link_to "薬剤師", new_pharmacist_registration_path, class:"btn" %>
    <%= link_to "学生", new_student_registration_path, class:"btn" %>
  </div>
  <div id="bg_black" class="bg_black"></div>
</div>

app/views/shared/_profile_image.html.erb
<% if profile.image? %>
  <%= image_tag profile.image.thumb.url, class: "user_icon" %>
<% else %>
  <%= image_tag "/assets/default.png", class: "user_icon default" %>
<% end %>

app/views/shared/_sign_up_modal.html.erb
<div id="popup_sign_up" class="popup">
  <div class="popup_inner">
    <div id="sign_up_close" class="close_btn"><i class="fas fa-times" aria-hidden="true"></i></div>
    <h2 class="title_border">新規会員登録</h2>
    <p>あなたは薬剤師ですか？</p>
    <p>学生ですか？</p>
    <%= link_to "薬剤師", new_pharmacist_registration_path, class:"btn" %>
    <%= link_to "学生", new_student_registration_path, class:"btn" %>
  </div>
  <div id="sign_up_black" class="bg_black"></div>
</div>

app/views/shared/_sign_up_page.html.erb
<% provide(:title, "新規登録") %>
<div class="form">
  <h2>新規登録(<%= user_type %>)</h2>
  <div class="form_contents">
    <%= form_with model: resource, scope: resource_name, url: registration_path(resource_name) do |f| %>
      <%= render "shared/error_messages", resource: resource %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
        (<%= @minimum_password_length %> 文字以上)
        <% end %><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
      </div>

      <div class="actions">
        <%= f.submit "メールアドレスで登録", class: "btn" %>
      </div>
    <% end %>

    <%= render "shared/links" %>
  </div>
</div>
<%= render "shared/sign_up_modal" %>
<%= render "shared/log_in_modal" %>