config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get :concepts, to: 'concepts#index'

  devise_for :pharmacists, controllers: {
                            sessions:      'pharmacists/sessions',
                            passwords:     'pharmacists/passwords',
                            registrations: 'pharmacists/registrations'
                          }, path_names: {
                            sign_in: 'login', sign_out: 'logout'
                          }
  devise_for :students, controllers: {
                          sessions:      'students/sessions',
                          passwords:     'students/passwords',
                          registrations: 'students/registrations'
                        }, path_names: {
                          sign_in: 'login', sign_out: 'logout'
                        }

  devise_scope :pharmacist do
    post 'pharmacists/guest_log_in', to: 'pharmacists/sessions#new_guest'
  end

  devise_scope :student do
    post 'students/guest_log_in', to: 'students/sessions#new_guest'
  end

  resources :pharmacists, only: :show
  resources :students, only: :show
  resources :pharmacist_profiles, except: [:index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :student_profiles, except: [:index, :destroy]

  resources :relationships, only: [:create, :update, :destroy]

  resources :rooms, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pharmacist_profile.rb
class PharmacistProfile < ApplicationRecord
  belongs_to :pharmacist

  mount_uploader :image, PharmacistImageUploader

  validates :name, presence: true, length: { maximum: 255 }
  validates :work_place, presence: true, length: { maximum: 255 }
  validates :work_place_type, presence: true
  validates :university, presence: true, length: { maximum: 255 }
  validates :introduction, presence: true, length: { maximum: 1000 }
  validate :image_size

  enum work_place_type: {
    調剤薬局: 0, ドラッグストア: 1, 病院: 2
  }

  enum work_location: {
    "--------------":0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
    沖縄県:47
  }

  private

    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "画像は5MB以下で登録してください。")
      end
    end
end

app/controllers/pharmacist_profiles_controller.rb
class PharmacistProfilesController < ApplicationController
  before_action :authenticate_pharmacist!, except: [:search, :show]
  before_action :authenticate_user!, only: [:show]
  before_action :profile_unregistered, only: [:new, :create]
  before_action :correct_pharmacist, only: [:edit, :update]

  def new
    @pharmacist_profile = PharmacistProfile.new
  end

  def create
    @pharmacist_profile = current_pharmacist.build_pharmacist_profile(pharmacist_profile_params)
    if @pharmacist_profile.save
      flash[:notice] = "プロフィールを登録しました。"
      redirect_to pharmacist_path(current_pharmacist)
    else
      render "new"
    end
  end

  def show
    @pharmacist_profile = PharmacistProfile.find(params[:id])
    @pharmacist = @pharmacist_profile.pharmacist
  end

  def edit
  end

  def update
    if @pharmacist_profile.update(pharmacist_profile_params)
      flash[:notice] = "プロフィールを更新しました。"
      redirect_to pharmacist_path(current_pharmacist)
    else
      render "edit"
    end
  end

  def search
    @q = PharmacistProfile.ransack(params[:q])
    @q.sorts = 'id desc' if @q.sorts.empty?
    @results = @q.result.page(params[:page]).per(10)
  end


  private

    def pharmacist_profile_params
      params.require(:pharmacist_profile).permit(:name, :image, :work_place, :work_place_type,
                                            :work_location, :university, :introduction, :remove_image)
    end

    def profile_unregistered
      if current_pharmacist.pharmacist_profile && current_pharmacist.pharmacist_profile.id
        redirect_to root_path
      end
    end

    def correct_pharmacist
      @pharmacist_profile = PharmacistProfile.find(params[:id])
      unless @pharmacist_profile == current_pharmacist.pharmacist_profile
        redirect_to root_path
      end
    end
end

app/views/pharmacist_profiles/_follow.html.erb
<%= form_with model: current_student.relationships.build do |f| %>
  <div><%= hidden_field_tag :pharmacist_id, pharmacist_profile.pharmacist_id %></div>
  <%= f.submit "トークを申請する", class: "btn" %>
<% end %>

app/views/pharmacist_profiles/_follow_request.html.erb
<% relationship = Relationship.find_by(pharmacist_id: @pharmacist.id, student_id: current_student.id) %>
<% if relationship && !relationship.allow %>
  <%= render "pharmacist_profiles/unfollow", pharmacist_profile: @pharmacist_profile, pharmacist: @pharmacist %>
<% elsif relationship && relationship.allow %>
  <p class="gray_color">トーク中</p>
<% elsif @pharmacist.pharmacist_relationship_limit %>
  <p class="gray_color"><%= @pharmacist_profile.name %>さんのトーク相手の数が上限に達しました</p>
<% else %>
  <%= render "pharmacist_profiles/follow", pharmacist_profile: @pharmacist_profile %>
<% end %>

app/views/pharmacist_profiles/_pharmacist_list.html.erb
<div class="search_pharmacist_profile">
  <div class="top_information">
    <%= render "shared/profile_image", profile: result %>
    <div>
      <h3><%= result.name %></h3>
      <p><small><%= result.work_place_type %></small></p>
      <p><small><i class="fas fa-map-marker-alt" aria-hidden="true"></i><%= result.work_location %></small></p>
    </div>
  </div>
  <div class="information">
    <p><span class="blue_marker">勤務先</span>　<%= result.work_place %></p>
    <p><span class="orange_marker">出身大学</span>　<%= result.university %></p>
  </div>
  <div class="introduction">
    <small><%= safe_join(result.introduction.split("\n"), tag(:br)) %></small>
  </div>
  <%= link_to "詳細", pharmacist_profile_path(result), class: "btn" %>
</div>

app/views/pharmacist_profiles/_unfollow.html.erb
<%= form_with model: current_student.relationships.find_by(pharmacist_id: pharmacist.id),
       html: { method: :delete } do |f| %>
  <div><%= hidden_field_tag :pharmacist_id, pharmacist_profile.pharmacist_id %></div>
  <%= f.submit "トーク申請を解除する", class: "unfollow" %>
<% end %>

app/views/pharmacist_profiles/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<%= render "shared/error_messages", resource: @pharmacist_profile %>
<div class="form_profile">
  <h2>プロフィール編集</h2>
  <div class="form_contents">
    <%= form_with model: @pharmacist_profile do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "ファーマ太郎" %>

      <%= f.label :image %>
      <%= f.file_field :image %>
      <% if @pharmacist_profile.image? %>
        <div class="edit_image">
          <%= image_tag @pharmacist_profile.image.thumb.url, class: "user_icon" %>
          <%= f.check_box :remove_image %>
          <%= f.label :remove_image %>
        </div>
      <% end %>

      <%= f.label :work_place %>
      <%= f.text_field :work_place, placeholder: "Pharma薬局" %>

      <%= f.label :work_place_type %>
      <div class="work_place_type">
        <%= f.radio_button :work_place_type, :調剤薬局, checked: "checked" %>
        <%= f.label :work_place_type_調剤薬局, "調剤薬局" %>
        <%= f.radio_button :work_place_type, :ドラッグストア %>
        <%= f.label :work_place_type_ドラッグストア, "ドラッグストア" %>
        <%= f.radio_button :work_place_type, :病院 %>
        <%= f.label :work_place_type_病院, "病院" %>
      </div>

      <%= f.label :work_location %>
      <%= f.select :work_location, PharmacistProfile.work_locations.keys, {} %>

      <%= f.label :university %>
      <%= f.text_field :university, placeholder: "Pharma大学" %>

      <%= f.label :introduction %>
      <%= f.text_area :introduction %>

      <%= f.submit "更新", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/pharmacist_profiles/new.html.erb
<% provide(:title, "プロフィール登録") %>
<%= render "shared/error_messages", resource: @pharmacist_profile %>
<%= render "shared/flash" %>
<div class="form_profile">
  <h2>プロフィール登録</h2>
  <%= form_with model: @pharmacist_profile do |f| %>
    <%= f.hidden_field :name, value: "テスト太郎" %>
    <%= f.hidden_field :work_place, value: "テスト薬局" %>
    <%= f.hidden_field :work_place_type, value: "調剤薬局" %>
    <%= f.hidden_field :work_location, value: "北海道" %>
    <%= f.hidden_field :university, value: "テスト大学" %>
    <%= f.hidden_field :introduction, value: "テストテスト" %>
    <%= f.submit "テストプロフィールで登録", class: "test_profile" %>
  <% end %>
  <div class="form_contents">
    <%= form_with model: @pharmacist_profile do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "ファーマ太郎" %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.label :work_place %>
      <%= f.text_field :work_place, placeholder: "Pharma薬局" %>

      <%= f.label :work_place_type %>
      <div class="work_place_type">
        <%= f.radio_button :work_place_type, :調剤薬局, checked: "checked" %>
        <%= f.label :work_place_type_調剤薬局, "調剤薬局" %>
        <%= f.radio_button :work_place_type, :ドラッグストア %>
        <%= f.label :work_place_type_ドラッグストア, "ドラッグストア" %>
        <%= f.radio_button :work_place_type, :病院 %>
        <%= f.label :work_place_type_病院, "病院" %>
      </div>

      <%= f.label :work_location %>
      <%= f.select :work_location, PharmacistProfile.work_locations.keys, {} %>

      <%= f.label :university %>
      <%= f.text_field :university, placeholder: "Pharma大学" %>

      <%= f.label :introduction %>
      <%= f.text_area :introduction %>

      <%= f.submit "登録", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/pharmacist_profiles/search.html.erb
<% provide(:title, "検索結果") %>
<div class="search_result">
  <h2>検索結果 <%= @results.total_count %> 人中
  <%= @results.offset_value %> 〜 <%=@results.offset_value + @results.length %> 人</h2>
  <%= paginate @results %>
  <%= render partial: "pharmacist_list", collection: @results, as: "result" %>
  <%= paginate @results %>
</div>
<%= render "shared/sign_up_modal" %>
<%= render "shared/log_in_modal" %>

app/views/pharmacist_profiles/show.html.erb
<% provide(:title, @pharmacist_profile.name) %>
<%= render "shared/flash" %>
<div class="profile_show">
  <div class="profile_show_content">
    <h2>基本情報</h2>
    <div class="information">
      <%= render "shared/profile_image", profile: @pharmacist_profile %>
      <div>
        <p><strong><%= @pharmacist_profile.name %></strong></p>
        <p><small><%= @pharmacist_profile.work_place_type %></small></p>
        <p><small><i class="fas fa-map-marker-alt" aria-hidden="true"></i><%= @pharmacist_profile.work_location %></small></p>
      </div>
    </div>
    <h2>勤務先・出身大学</h2>
    <div class="information">
      <p>
        <span><%= @pharmacist_profile.work_place %></span>
        <span><%= @pharmacist_profile.university %></span>
      </p>
    </div>
    <h2>プロフィール</h2>
    <div class="profile">
      <small><%= safe_join(@pharmacist_profile.introduction.split("\n"), tag(:br)) %></small>
    </div>
  </div>
  <% if pharmacist_signed_in? %>
    <% if @pharmacist == current_pharmacist %>
      <%= link_to "編集する", edit_pharmacist_profile_path(@pharmacist_profile), class: "btn" %>
    <% end %>
  <% elsif student_signed_in? %>
    <%= render "pharmacist_profiles/follow_request" %>
  <% end %>
</div>