config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get :concepts, to: 'concepts#index'

  devise_for :pharmacists, controllers: {
                            sessions:      'pharmacists/sessions',
                            passwords:     'pharmacists/passwords',
                            registrations: 'pharmacists/registrations'
                          }, path_names: {
                            sign_in: 'login', sign_out: 'logout'
                          }
  devise_for :students, controllers: {
                          sessions:      'students/sessions',
                          passwords:     'students/passwords',
                          registrations: 'students/registrations'
                        }, path_names: {
                          sign_in: 'login', sign_out: 'logout'
                        }

  devise_scope :pharmacist do
    post 'pharmacists/guest_log_in', to: 'pharmacists/sessions#new_guest'
  end

  devise_scope :student do
    post 'students/guest_log_in', to: 'students/sessions#new_guest'
  end

  resources :pharmacists, only: :show
  resources :students, only: :show
  resources :pharmacist_profiles, except: [:index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :student_profiles, except: [:index, :destroy]

  resources :relationships, only: [:create, :update, :destroy]

  resources :rooms, only: [:create, :show, :destroy] do
    resources :messages, only: :create
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to concepts_path do %>
    <p><i class="fas fa-chevron-circle-right"></i>Pharma Talkについて</p>
  <% end %>
  <p><small>&copy; <%= Date.current.strftime('%Y') %> Pharma Talk</small></p>
</footer>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header_content">
    <h1><%= link_to "Pharma Talk", root_path %></h1>
    <ul class="header_menu">
      <% if no_one_is_logged_in %>
        <li class="js_log_in"><i class="fas fa-sign-in-alt"></i>ログイン</li>
        <li class="js_sign_up"><i class="fas fa-user-edit"></i>新規登録</li>
      <% elsif pharmacist_signed_in? %>
        <%= render "layouts/pharmacist_header" %>
      <% else %>
        <%= render "layouts/student_header" %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_pharmacist_drop_down.html.erb
<ul>
  <li><%= link_to "マイページ", pharmacist_path(current_pharmacist) %></li>
  <li><%= link_to "プロフィール", pharmacist_profile_path(current_pharmacist.pharmacist_profile.id) %></li>
  <li><%= link_to "アカウント編集", edit_pharmacist_registration_path %></li>
  <li><%= link_to "ログアウト", destroy_pharmacist_session_path, method: :delete %></li>
</ul>

app/views/layouts/_pharmacist_header.erb
<% if !current_pharmacist.pharmacist_profile || !current_pharmacist.pharmacist_profile.id %>
  <li><%= link_to "プロフィールを登録", new_pharmacist_profile_path %></li>
  <li><%= link_to "ログアウト", destroy_pharmacist_session_path, method: :delete %>
<% else %>
  <div class="hamburger_menu">
    <input type="checkbox" id="menu_btn_check">
    <label for="menu_btn_check" class="menu_btn"><span></span></label>
    <li class="drop_down">
      <% if current_pharmacist.pharmacist_profile.image? %>
        <%= image_tag current_pharmacist.pharmacist_profile.image.thumb.url, class: "user_icon" %>
      <% else %>
        <%= image_tag "/assets/default.png", class: "user_icon default" %>
      <% end %>
        <%= render "layouts/pharmacist_drop_down"%>
    </li>
  </div>
<% end %>

app/views/layouts/_student_drop_down.html.erb
<ul>
  <li><%= link_to "マイページ", student_path(current_student) %></li>
  <li><%= link_to "プロフィール", student_profile_path(current_student.student_profile.id) %></li>
  <li><%= link_to "アカウント編集", edit_student_registration_path %></li>
  <li><%= link_to "ログアウト", destroy_student_session_path, method: :delete %></li>
</ul>

app/views/layouts/_student_header.html.erb
<% if !current_student.student_profile || !current_student.student_profile.id %>
  <li><%= link_to "プロフィールを登録", new_student_profile_path %></li>
  <li><%= link_to "ログアウト", destroy_student_session_path, method: :delete %></li>
<% else %>
  <div class="hamburger_menu">
    <input type="checkbox" id="menu_btn_check">
    <label for="menu_btn_check" class="menu_btn"><span></span></label>
    <li class="drop_down">
      <% if current_student.student_profile.image? %>
        <%= image_tag current_student.student_profile.image.thumb.url, class: "user_icon" %>
      <% else %>
        <%= image_tag "/assets/default.png", class: "user_icon default" %>
      <% end %>
        <%= render "layouts/student_drop_down"%>
    </li>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :js %>
  </head>

  <body>
    <%= render "layouts/header" unless controller.controller_name == "rooms" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" unless controller.controller_name == "rooms" %>
    </div>
  </body>
</html>